### ISSUE TITLE
Missing link in the Web site

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-gui#56] opened 2015-02-04 08:58 UTC
_From @bortzmeyer on February 3, 2015 15:48_

FAQ in French, the text says "Le lien suivant, par exemple, renvoie sur les résultats de la dernière analyse de "afnic.fr":" but there is no "lien suivant".

_Copied from original issue: dotse/zonemaster#332_

**Comment by sandoche2k** [comment] 2015-04-09 11:33
@MTO could be closed

**Comment by pahi** [comment] 2015-05-12 08:07
Close this ticket?

**Comment by bortzmeyer** [comment] 2015-05-12 11:56
@pahl Of course not, the problem is still there.

**Comment by sandoche2k** [comment] 2015-05-17 15:15
@pawal assignee @mtoma and for release .2

**Comment by sandoche2k** [comment] 2015-06-18 08:38
@mtoma can you finish and close this

**Closed** 2015-06-23 08:47 UTC
Labels: translation
